// <auto-generated />
using LoginStartMenu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginStartMenu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250303211734_Aggiunta-Anagrafica-Immagine")]
    partial class AggiuntaAnagraficaImmagine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Anagrafica", b =>
                {
                    b.Property<int>("IdAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnagrafica"));

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnagrafica");

                    b.ToTable("Anagrafica");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Immagine", b =>
                {
                    b.Property<int>("IdImmagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImmagine"));

                    b.Property<string>("Img1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImmagine");

                    b.ToTable("Immagine");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Ruolo", b =>
                {
                    b.Property<int>("IdRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuolo"));

                    b.Property<string>("NomeRuolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRuolo");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Utente", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtente"));

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtente");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteAnagrafica", b =>
                {
                    b.Property<int>("IdUtenteAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtenteAnagrafica"));

                    b.Property<int>("IdAnagrafica")
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.HasKey("IdUtenteAnagrafica");

                    b.HasIndex("IdAnagrafica");

                    b.HasIndex("IdUtente");

                    b.ToTable("UtenteAnagrafica");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteImmagine", b =>
                {
                    b.Property<int>("IdUtenteImmagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtenteImmagine"));

                    b.Property<int>("IdImmagine")
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.HasKey("IdUtenteImmagine");

                    b.HasIndex("IdImmagine");

                    b.HasIndex("IdUtente");

                    b.ToTable("UtenteImmagine");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteRuolo", b =>
                {
                    b.Property<int>("IdUtenteRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtenteRuolo"));

                    b.Property<int>("IdRuolo")
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.HasKey("IdUtenteRuolo");

                    b.HasIndex("IdRuolo");

                    b.HasIndex("IdUtente");

                    b.ToTable("UtentiRuoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteAnagrafica", b =>
                {
                    b.HasOne("LoginStartMenu.Models.Entity.Anagrafica", "Anagrafica")
                        .WithMany("UtentiAnagrafiche")
                        .HasForeignKey("IdAnagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginStartMenu.Models.Entity.Utente", "Utente")
                        .WithMany("UtentiAnagrafiche")
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anagrafica");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteImmagine", b =>
                {
                    b.HasOne("LoginStartMenu.Models.Entity.Immagine", "Immagine")
                        .WithMany("UtentiImmagini")
                        .HasForeignKey("IdImmagine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginStartMenu.Models.Entity.Utente", "Utente")
                        .WithMany("UtentiImmagini")
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Immagine");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteRuolo", b =>
                {
                    b.HasOne("LoginStartMenu.Models.Entity.Ruolo", "Ruolo")
                        .WithMany("UtentiRuoli")
                        .HasForeignKey("IdRuolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginStartMenu.Models.Entity.Utente", "Utente")
                        .WithMany("UtentiRuoli")
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Anagrafica", b =>
                {
                    b.Navigation("UtentiAnagrafiche");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Immagine", b =>
                {
                    b.Navigation("UtentiImmagini");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Ruolo", b =>
                {
                    b.Navigation("UtentiRuoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Utente", b =>
                {
                    b.Navigation("UtentiAnagrafiche");

                    b.Navigation("UtentiImmagini");

                    b.Navigation("UtentiRuoli");
                });
#pragma warning restore 612, 618
        }
    }
}
