// <auto-generated />
using LoginStartMenu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginStartMenu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250305214342_iniziale5")]
    partial class iniziale5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Anagrafica", b =>
                {
                    b.Property<int>("IdAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnagrafica"));

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnagrafica");

                    b.ToTable("Anagrafiche");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Immagine", b =>
                {
                    b.Property<int>("IdImmagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImmagine"));

                    b.Property<string>("Img1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImmagine");

                    b.ToTable("Immagini");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Ruolo", b =>
                {
                    b.Property<int>("IdRuolo")
                        .HasColumnType("int");

                    b.Property<string>("NomeRuolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRuolo");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Utente", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtente"));

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAnagrafica")
                        .HasColumnType("int");

                    b.Property<int>("IdImmagine")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtente");

                    b.HasIndex("IdAnagrafica")
                        .IsUnique();

                    b.HasIndex("IdImmagine")
                        .IsUnique();

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteRuolo", b =>
                {
                    b.Property<int>("IdUtenteRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtenteRuolo"));

                    b.Property<int>("IdRuolo")
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.HasKey("IdUtenteRuolo");

                    b.HasIndex("IdRuolo");

                    b.HasIndex("IdUtente");

                    b.ToTable("UtentiRuoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Utente", b =>
                {
                    b.HasOne("LoginStartMenu.Models.Entity.Anagrafica", "Anagrafica")
                        .WithOne("Utente")
                        .HasForeignKey("LoginStartMenu.Models.Entity.Utente", "IdAnagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginStartMenu.Models.Entity.Immagine", "Immagine")
                        .WithOne("Utente")
                        .HasForeignKey("LoginStartMenu.Models.Entity.Utente", "IdImmagine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anagrafica");

                    b.Navigation("Immagine");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.UtenteRuolo", b =>
                {
                    b.HasOne("LoginStartMenu.Models.Entity.Ruolo", "Ruolo")
                        .WithMany("UtentiRuoli")
                        .HasForeignKey("IdRuolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginStartMenu.Models.Entity.Utente", "Utente")
                        .WithMany("UtentiRuoli")
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Anagrafica", b =>
                {
                    b.Navigation("Utente")
                        .IsRequired();
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Immagine", b =>
                {
                    b.Navigation("Utente")
                        .IsRequired();
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Ruolo", b =>
                {
                    b.Navigation("UtentiRuoli");
                });

            modelBuilder.Entity("LoginStartMenu.Models.Entity.Utente", b =>
                {
                    b.Navigation("UtentiRuoli");
                });
#pragma warning restore 612, 618
        }
    }
}
